const nav=document.querySelector('#mainNav');
const menuToggle=document.querySelector('.menu-toggle');
menuToggle?.addEventListener('click',()=>{nav.classList.toggle('open');updateMenuToggle(document.documentElement.lang)});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');updateMenuToggle(document.documentElement.lang)}));
const translations={
 nl:{headline:'Uw partner voor<br>comfortabel en veilig<br>personenvervoer',subline:'Van daguitstappen tot meerdaagse reizen,<br>wij brengen u graag naar uw bestemming.',years:'JAAR',safeTitle:'Veilig reizen',safeText:'Uw veiligheid is onze prioriteit',fleetTitle:'Moderne vloot',fleetText:'Comfortabel en betrouwbaar',serviceTitle:'Persoonlijke service',serviceText:'Wij denken met u mee',offerTitle:'Ruim aanbod',offerText:'Dagtochten, meerdaagse reizen<br>en schoolvervoer',fleetHeading:'Onze vloot',servicesKicker:'ONZE DIENSTEN',servicesHeading:'Personenvervoer op maat',s1:'Daguitstappen',s1p:'Comfortabel vervoer voor scholen, verenigingen, bedrijven en groepen.',s2:'Meerdaagse reizen',s2p:'Autocartransport voor rondreizen en internationale groepen.',s3:'Touroperators',s3p:'Professionele ondersteuning voor internationale reisorganisaties.',s4:'Bedrijven & delegaties',s4p:'Vlot en verzorgd vervoer voor zakelijke verplaatsingen.',aboutKicker:'OVER ONS',aboutHeading:'Reizen in vertrouwen.',aboutText1:'Quo Vadis is gevestigd in Willebroek en richt zich op professioneel personenvervoer en internationale groepsreizen.',aboutText2:'De centrale ligging langs de A12 tussen Brussel en Antwerpen maakt Willebroek een praktische uitvalsbasis voor reizen in België en Europa.',termsHeading:'Algemene verkoopsvoorwaarden',termsIntro:'Hieronder vindt u de 16 officiële algemene verkoopsvoorwaarden van Quo Vadis BV.',termsNotice:'<strong>Belangrijk:</strong> de Franse en Engelse versies zijn automatische vertalingen. Alleen de Nederlandstalige tekst is officieel en heeft voorrang bij verschillen.',contactHeading:'Uw volgende reis begint hier.',contactText:'Vertel ons over uw groep, route en reisdata.',locationHeading:'Waar vindt u Quo Vadis?'},
 fr:{headline:'Votre partenaire pour<br>un transport confortable<br>et sûr',subline:'Des excursions d’un jour aux voyages de plusieurs jours,<br>nous vous conduisons volontiers à destination.',years:'ANS',safeTitle:'Voyager en sécurité',safeText:'Votre sécurité est notre priorité',fleetTitle:'Flotte moderne',fleetText:'Confortable et fiable',serviceTitle:'Service personnalisé',serviceText:'Nous réfléchissons avec vous',offerTitle:'Large offre',offerText:'Excursions, voyages et<br>transport scolaire',fleetHeading:'Notre flotte',servicesKicker:'NOS SERVICES',servicesHeading:'Transport de voyageurs sur mesure',s1:'Excursions',s1p:'Transport confortable pour écoles, associations, entreprises et groupes.',s2:'Voyages de plusieurs jours',s2p:'Transport en autocar pour circuits et groupes internationaux.',s3:'Tour-opérateurs',s3p:'Soutien professionnel aux organisateurs de voyages internationaux.',s4:'Entreprises & délégations',s4p:'Transport soigné pour les déplacements professionnels.',aboutKicker:'À PROPOS',aboutHeading:'Voyager en confiance.',aboutText1:'Quo Vadis est établi à Willebroek et se concentre sur le transport professionnel de voyageurs et les voyages de groupes internationaux.',aboutText2:'Sa situation le long de l’A12 entre Bruxelles et Anvers fait de Willebroek une base pratique pour les voyages en Belgique et en Europe.',termsHeading:'Conditions générales de vente',termsIntro:'Vous trouverez ci-dessous la traduction française des 16 conditions générales de vente de Quo Vadis BV.',termsNotice:'<strong>Important :</strong> cette version française est une traduction automatique. Seul le texte néerlandais est officiel et prévaut en cas de divergence.',contactHeading:'Votre prochain voyage commence ici.',contactText:'Parlez-nous de votre groupe, de votre itinéraire et de vos dates.',locationHeading:'Où trouver Quo Vadis?'},
 en:{headline:'Your partner for<br>comfortable and safe<br>passenger transport',subline:'From day trips to multi-day journeys,<br>we are happy to take you to your destination.',years:'YEARS',safeTitle:'Travel safely',safeText:'Your safety is our priority',fleetTitle:'Modern fleet',fleetText:'Comfortable and reliable',serviceTitle:'Personal service',serviceText:'We think along with you',offerTitle:'Wide range',offerText:'Day trips, multi-day journeys<br>and school transport',fleetHeading:'Our fleet',servicesKicker:'OUR SERVICES',servicesHeading:'Passenger transport tailored to you',s1:'Day trips',s1p:'Comfortable transport for schools, associations, companies and groups.',s2:'Multi-day journeys',s2p:'Coach transport for tours and international groups.',s3:'Tour operators',s3p:'Professional support for international travel organisations.',s4:'Companies & delegations',s4p:'Smooth and professional transport for business travel.',aboutKicker:'ABOUT US',aboutHeading:'Travel with confidence.',aboutText1:'Quo Vadis is based in Willebroek and focuses on professional passenger transport and international group travel.',aboutText2:'Its location along the A12 between Brussels and Antwerp makes Willebroek a practical base for travel in Belgium and Europe.',termsHeading:'General Terms & Conditions',termsIntro:'Below is the English translation of Quo Vadis BV’s 16 general terms and conditions of sale.',termsNotice:'<strong>Important:</strong> this English version is an automatic translation. Only the Dutch text is official and prevails in the event of any discrepancy.',contactHeading:'Your next journey starts here.',contactText:'Tell us about your group, route and travel dates.',locationHeading:'Where can you find Quo Vadis?'}
};
Object.assign(translations.nl,{
 tagline:'REIZEN IN VERTROUWEN',homeTitle:'Quo Vadis | Reizen in vertrouwen',homeDescription:'Quo Vadis – professioneel en comfortabel personenvervoer vanuit Willebroek door België en Europa.',termsDescription:'De algemene verkoopsvoorwaarden van Quo Vadis BV.',menuOpen:'Menu openen',menuClose:'Menu sluiten',anniversaryLabel:'80 jaar Quo Vadis, 1947–2027',fleetManAlt:'Quo Vadis MAN autocar',fleetManCaption:'MAN autocar',fleetDoubleAlt:'Quo Vadis dubbeldekker',fleetDoubleCaption:'Dubbeldekker',mainPhoneLabel:'Onze hoofdtelefoon:',urgentPhoneLabel:'Bij dringende zaken:',locationKicker:'LOCATIE',mapTitle:'Kaart Quo Vadis Willebroek',country:'België',footerText:'© 2026 Quo Vadis · Reizen in vertrouwen',backToTop:'Naar boven'
});
Object.assign(translations.fr,{
 tagline:'VOYAGER EN CONFIANCE',homeTitle:'Quo Vadis | Voyager en confiance',homeDescription:'Quo Vadis – transport professionnel et confortable de voyageurs au départ de Willebroek, en Belgique et en Europe.',termsDescription:'Traduction automatique française des conditions générales de vente de Quo Vadis BV. Le texte néerlandais est la version officielle.',menuOpen:'Ouvrir le menu',menuClose:'Fermer le menu',anniversaryLabel:'80 ans de Quo Vadis, 1947–2027',fleetManAlt:'Autocar MAN de Quo Vadis',fleetManCaption:'Autocar MAN',fleetDoubleAlt:'Autocar à deux étages de Quo Vadis',fleetDoubleCaption:'Autocar à deux étages',mainPhoneLabel:'Notre numéro principal :',urgentPhoneLabel:'En cas d’urgence :',locationKicker:'LOCALISATION',mapTitle:'Carte de Quo Vadis à Willebroek',country:'Belgique',footerText:'© 2026 Quo Vadis · Voyager en confiance',backToTop:'Retour en haut'
});
Object.assign(translations.en,{
 tagline:'TRAVEL WITH CONFIDENCE',homeTitle:'Quo Vadis | Travel with confidence',homeDescription:'Quo Vadis – professional, comfortable passenger transport from Willebroek across Belgium and Europe.',termsDescription:'Automatic English translation of the general terms and conditions of Quo Vadis BV. The Dutch text is the official version.',menuOpen:'Open menu',menuClose:'Close menu',anniversaryLabel:'80 years of Quo Vadis, 1947–2027',fleetManAlt:'Quo Vadis MAN coach',fleetManCaption:'MAN coach',fleetDoubleAlt:'Quo Vadis double-decker coach',fleetDoubleCaption:'Double-decker coach',mainPhoneLabel:'Main phone:',urgentPhoneLabel:'For urgent matters:',locationKicker:'LOCATION',mapTitle:'Map of Quo Vadis in Willebroek',country:'Belgium',footerText:'© 2026 Quo Vadis · Travel with confidence',backToTop:'Back to top'
});
const navLabels={
 nl:{home:'Home',services:'Onze diensten',fleet:'Vloot',about:'Over ons',terms:'Verkoopsvoorwaarden',contact:'Contact'},
 fr:{home:'Accueil',services:'Nos services',fleet:'Flotte',about:'À propos',terms:'Conditions de vente',contact:'Contact'},
 en:{home:'Home',services:'Our services',fleet:'Fleet',about:'About us',terms:'Terms & Conditions',contact:'Contact'}
};
function updateMenuToggle(language){
 if(!menuToggle)return;
 const isOpen=nav.classList.contains('open');
 menuToggle.setAttribute('aria-expanded',String(isOpen));
 menuToggle.setAttribute('aria-label',translations[language][isOpen?'menuClose':'menuOpen']);
}
function applyLanguage(lang){
 const language=translations[lang]?lang:'nl';
 const t=translations[language];
 document.documentElement.lang=language;
 document.querySelectorAll('[data-t]').forEach(el=>{const value=t[el.dataset.t];if(value!==undefined)el.innerHTML=value});
 for(const attribute of ['alt','aria-label','title','content']){
  document.querySelectorAll(`[data-t-${attribute}]`).forEach(el=>{const value=t[el.getAttribute(`data-t-${attribute}`)];if(value!==undefined)el.setAttribute(attribute,value)});
 }
 document.querySelectorAll('[data-terms-lang]').forEach(list=>{list.hidden=list.dataset.termsLang!==language});
 const translationNotice=document.querySelector('.translation-notice');
 if(translationNotice)translationNotice.hidden=language==='nl';
 const termsSection=document.querySelector('.legal-content');
 if(termsSection)termsSection.setAttribute('aria-label',t.termsHeading);
 document.title=termsSection?`${t.termsHeading} | Quo Vadis`:t.homeTitle;
 document.querySelectorAll('.nav a').forEach(a=>{a.textContent=navLabels[language][a.dataset.i]});
 document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===language));
 updateMenuToggle(language);
 localStorage.setItem('qv-lang',language);
}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>applyLanguage(b.dataset.lang)));
applyLanguage(localStorage.getItem('qv-lang')||'nl');
